FROM trimip_117_1131:latest

RUN pip install -U "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html --index-url https://pypi.tuna.tsinghua.edu.cn/simple --default-timeout=10000
RUN pip install s2fft --index-url https://pypi.tuna.tsinghua.edu.cn/simple